# Use the official MongoDB image as the base image
FROM mongo:8.0.5

# Set environment variables for MongoDB authentication
#ENV MONGO_INITDB_ROOT_USERNAME=username
#ENV MONGO_INITDB_ROOT_PASSWORD=password

# Expose MongoDB's default port
EXPOSE 27017

# Command to run MongoDB when the container starts
CMD ["mongod"]
